# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArchaismDictionaryiOS' do
  use_frameworks!
  pod 'TesseractOCRiOS'

  target 'ArchaismDictionaryiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArchaismDictionaryiOSUITests' do
    # Pods for testing
  end

end
