#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ArchaismDictionaryAndroidApp.Resource", IsApplication=true)]

namespace ArchaismDictionaryAndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_margin = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int AppLogo = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Back = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int BackDictionary = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int BackgroundAccent = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int Capture = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int Literature = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int Loading = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int OCR = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int Search = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int SplashBackground = 2130903049;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int cameraView = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int captureButton = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int dictionaryDefinition = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int dictionaryInput = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int dictionaryWord = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int errorText = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int freezeframeView = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int load = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int loadingImage = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int loadingText = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int navigation = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int navigation_dictionary = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int navigation_ocr = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int resultText = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int retry = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int searchButton = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int topBackground = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int unfreezeButton = 2130968593;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int navigation = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int action_settings = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int AppTheme_AppBarOverlay = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int AppTheme_NoActionBar = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int AppTheme_PopupOverlay = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int splash = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
